<script>
"use strict";
// =====================================================================
//  SITE & TOWN MAPS (UI): floor plans you can walk through, and streets you can walk down.
//  SiteMap draws one floor of the place the party is in: walls, doors, stairs, furniture, people,
//  the party token and what's still unexplored. SitePanel lists what's in the room and what you can do.
//  TownMap draws a settlement's streets and buildings; tap a building to go inside.
// =====================================================================
const SU = 26;  // pixels per 5-foot square on floor plans
const TU = 15;  // pixels per unit on town maps
// --- furniture glyphs: simple top-down shapes, drawn in a w×h box (pixels) ---
function ObjGlyph({ o, style }){
  const W = o.w * SU, H = o.h * SU, k = o.kind; const wood = "#6b4a2e", woodL = "#8a6a44", iron = "#3a3a40", stone = "#8f8a80", cloth = "#7a3a3a", gold = "#e6bd55";
  const box = (fill, stroke = "#2a1f15", rx = 3, inset = 3) => html`<rect x=${inset} y=${inset} width=${W - inset * 2} height=${H - inset * 2} rx=${rx} fill=${fill} stroke=${stroke} strokeWidth="1.2"/>`;
  const circ = (fill, r = Math.min(W, H) / 2 - 3, stroke = "#2a1f15") => html`<circle cx=${W / 2} cy=${H / 2} r=${r} fill=${fill} stroke=${stroke} strokeWidth="1.2"/>`;
  const fire = html`<g><circle cx=${W / 2} cy=${H / 2} r=${Math.min(W, H) / 2 - 4} fill="#ff9a3c" opacity=".9"/><path d=${`M${W / 2 - 5},${H / 2 + 5} q5,-16 10,0 q-3,-6 -5,-10 q-2,4 -5,10z`} fill="#ffe08a"/></g>`;
  const state = o.state || ""; const broken = /broken|burned|smashed/.test(state) || k === "debris";
  switch (k){
    case "table": return html`<g>${box(broken ? "#5a4030" : woodL, "#2a1f15", 4)}<rect x="6" y="6" width=${W - 12} height=${H - 12} fill="none" stroke="#5a3f28" strokeWidth=".8"/>${broken && html`<path d=${`M4,4 L${W - 4},${H - 4} M${W - 4},4 L4,${H - 4}`} stroke="#2a1f15" strokeWidth="1.5"/>`}</g>`;
    case "chair": case "stool": return html`<g><rect x="7" y="7" width=${W - 14} height=${H - 14} rx="3" fill=${woodL} stroke="#2a1f15" strokeWidth="1"/><rect x="7" y="5" width=${W - 14} height="3" fill=${wood}/></g>`;
    case "bar": return html`<g>${box(wood, "#2a1f15", 2)}<rect x="5" y="5" width=${W - 10} height="6" fill=${woodL}/>${Array.from({ length: Math.max(1, o.w) }, (_, i) => html`<circle key=${i} cx=${10 + i * SU} cy=${H - 9} r="3" fill="#c9a24a" stroke="#5a3f28" strokeWidth=".6"/>`)}</g>`;
    case "fireplace": case "forge": return html`<g>${box(stone, "#2a1f15", 2)}<rect x="4" y="4" width=${W - 8} height="5" fill="#5a554d"/>${/extinguished|cold/.test(state) ? html`<circle cx=${W / 2} cy=${H / 2 + 2} r="5" fill="#4a4440"/>` : fire}</g>`;
    case "campfire": case "brazier": return html`<g>${k === "brazier" ? circ(iron, 9) : html`<circle cx=${W / 2} cy=${H / 2} r="9" fill="#4a4440" stroke="#2a1f15"/>`}${/extinguished|cold/.test(state) ? null : html`<circle cx=${W / 2} cy=${H / 2} r="5" fill="#ff9a3c"/><circle cx=${W / 2} cy=${H / 2 - 1} r="2.5" fill="#ffe08a"/>`}</g>`;
    case "torch": case "candles": return html`<g><circle cx=${W / 2} cy=${H / 2} r=${k === "torch" ? 4 : 5} fill="#ffe08a" opacity=".95"/><circle cx=${W / 2} cy=${H / 2} r="2" fill="#ff9a3c"/></g>`;
    case "bed": return html`<g>${box("#c9b89a", "#2a1f15", 3)}<rect x="5" y="5" width=${Math.min(W, H) - 10} height=${H - 10} rx="2" fill="#efe6d2"/><rect x=${Math.min(W, H) - 2} y="5" width=${W - Math.min(W, H) - 3} height=${H - 10} fill=${cloth} opacity=".85"/></g>`;
    case "bedroll": case "hay": case "hammock": return html`<g>${box(k === "hay" ? "#c9a24a" : "#9a8a62", "#2a1f15", 6)}<path d=${`M6,${H / 2} h${W - 12}`} stroke="#5a4328" strokeWidth="1" strokeDasharray="3 2"/></g>`;
    case "shelf": case "bookshelf": case "rack": case "wardrobe": return html`<g>${box(wood, "#2a1f15", 1)}${Array.from({ length: Math.max(2, o.w * 3) }, (_, i) => html`<rect key=${i} x=${5 + i * ((W - 10) / Math.max(2, o.w * 3))} y="6" width=${(W - 10) / Math.max(2, o.w * 3) - 2} height=${H - 12} fill=${k === "rack" ? "#9aa0a8" : k === "wardrobe" ? woodL : ["#8b3a3a","#3a5a8b","#6b8b3a","#c9a24a","#7a4a8b"][i % 5]} opacity=".85"/>`)}</g>`;
    case "chest": case "coffin": case "sarcophagus": case "hoard": return html`<g>${k === "hoard" ? html`<ellipse cx=${W / 2} cy=${H / 2} rx=${W / 2 - 3} ry=${H / 2 - 3} fill=${gold} stroke="#a57f22"/><circle cx=${W / 2 - 6} cy=${H / 2 - 3} r="3" fill="#fff2b0"/><circle cx=${W / 2 + 7} cy=${H / 2 + 4} r="2.5" fill="#fff2b0"/>` : html`${box(k === "chest" ? (o.looted ? "#7a5a3a" : "#8a5a2a") : stone, "#2a1f15", 3)}<rect x="4" y=${H / 2 - 1} width=${W - 8} height="2" fill="#2a1f15" opacity=".5"/>${o.locked && !o.unlocked ? html`<circle cx=${W / 2} cy=${H / 2} r="3" fill=${gold}/>` : o.open || o.looted ? html`<rect x="6" y="6" width=${W - 12} height=${H / 2 - 8} fill="#1a1410" opacity=".6"/>` : null}`}</g>`;
    case "crate": case "sack": case "keg": case "barrel": return html`<g>${k === "barrel" || k === "keg" ? html`<circle cx=${W / 2} cy=${H / 2} r=${Math.min(W, H) / 2 - 4} fill=${woodL} stroke="#2a1f15" strokeWidth="1.2"/><circle cx=${W / 2} cy=${H / 2} r=${Math.min(W, H) / 2 - 8} fill="none" stroke="#5a3f28" strokeWidth="1"/>` : k === "sack" ? html`<ellipse cx=${W / 2} cy=${H / 2} rx=${W / 2 - 5} ry=${H / 2 - 4} fill="#b8a070" stroke="#2a1f15" strokeWidth="1"/>` : html`${box(woodL, "#2a1f15", 1)}<path d=${`M4,4 L${W - 4},${H - 4} M${W - 4},4 L4,${H - 4}`} stroke="#5a3f28" strokeWidth="1"/>`}</g>`;
    case "altar": return html`<g>${box("#b8b0a4", "#2a1f15", 2)}<rect x=${W / 2 - 2} y="6" width="4" height=${H - 12} fill="#e6bd55"/><rect x=${W / 2 - 7} y=${H / 2 - 2} width="14" height="4" fill="#e6bd55"/></g>`;
    case "statue": case "idol": return html`<g>${circ(k === "idol" ? "#5a4a3a" : "#a8a098", 9)}<circle cx=${W / 2} cy=${H / 2 - 3} r="3.5" fill=${k === "idol" ? "#3a2a1a" : "#e8e2d8"}/></g>`;
    case "pillar": return html`<g>${circ("#a8a098", 8)}${circ("#8f8a80", 5, "none")}</g>`;
    case "well": case "fountain": case "pool": return html`<g>${k === "pool" ? html`<rect x="3" y="3" width=${W - 6} height=${H - 6} rx="10" fill="#3a5a6a" stroke="#1a2a30" strokeWidth="1.2"/><path d=${`M8,${H / 2} q4,-3 8,0 t8,0 t8,0`} stroke="#7fa6b6" strokeWidth="1" fill="none"/>` : html`${circ("#8f8a80", Math.min(W, H) / 2 - 3)}${circ("#3a5a6a", Math.min(W, H) / 2 - 8, "none")}`}</g>`;
    case "lever": case "wheel": case "bell": return html`<g>${circ(iron, 7)}<rect x=${W / 2 - 1.5} y="4" width="3" height=${H / 2} fill="#c9a24a" transform=${o.state === "pulled" ? `rotate(40 ${W / 2} ${H / 2})` : ""}/></g>`;
    case "cage": case "bars": return html`<g>${box("none", "#3a3a40", 1)}${Array.from({ length: 4 }, (_, i) => html`<rect key=${i} x=${5 + i * ((W - 10) / 4)} y="4" width="2" height=${H - 8} fill="#3a3a40"/>`)}${o.prisoner && !o.prisoner.freed ? html`<circle cx=${W / 2} cy=${H / 2} r="4" fill="#d8b08a"/>` : null}</g>`;
    case "rubble": case "bones": case "debris": return html`<g>${[[6, 8, 5], [W - 10, H - 9, 4], [W / 2, H / 2 + 2, 6], [W / 2 - 8, H - 7, 3]].map(([x, y, r], i) => html`<circle key=${i} cx=${x} cy=${y} r=${r} fill=${k === "bones" ? "#e8e2d2" : k === "debris" ? woodL : "#8f8a80"} stroke="#2a1f15" strokeWidth=".8"/>`)}</g>`;
    case "cauldron": return html`<g>${circ(iron, 9)}${circ("#4f8a3f", 6, "none")}</g>`;
    case "lectern": case "desk": case "map": case "notice": case "plaque": return html`<g>${box(k === "notice" || k === "plaque" ? wood : woodL, "#2a1f15", 2)}<rect x="6" y="6" width=${W - 12} height=${H - 12} fill="#efe6d2"/><path d=${`M9,${H / 2 - 3} h${W - 18} M9,${H / 2 + 2} h${W - 22}`} stroke="#5a4328" strokeWidth="1"/></g>`;
    case "cart": case "boat": return html`<g>${box(k === "boat" ? wood : woodL, "#2a1f15", k === "boat" ? 12 : 3)}${k === "cart" ? html`<circle cx="7" cy=${H - 5} r="3" fill="#2a1f15"/><circle cx=${W - 7} cy=${H - 5} r="3" fill="#2a1f15"/>` : html`<path d=${`M8,${H / 2} h${W - 16}`} stroke="#2a1f15" strokeWidth="1"/>`}</g>`;
    case "painting": case "window": return html`<g>${box(k === "window" ? "#9ac" : "#8b3a3a", k === "window" ? "#2a1f15" : "#c9a24a", 1, 4)}</g>`;
    case "throne": return html`<g>${box("#8b3a3a", "#c9a24a", 2)}<rect x=${W / 2 - 4} y="4" width="8" height="5" fill="#e6bd55"/></g>`;
    case "grave": return html`<g>${box("#7a6a50", "#2a1f15", 2)}<rect x=${W / 2 - 1.5} y="5" width="3" height="10" fill="#c8c0b0"/><rect x=${W / 2 - 5} y="8" width="10" height="3" fill="#c8c0b0"/></g>`;
    case "web": return html`<g opacity=".8"><path d=${`M4,4 L${W - 4},${H - 4} M${W - 4},4 L4,${H - 4} M${W / 2},4 V${H - 4} M4,${H / 2} H${W - 4}`} stroke="#e8e2d8" strokeWidth="1"/><circle cx=${W / 2} cy=${H / 2} r="8" fill="none" stroke="#e8e2d8" strokeWidth="1"/><circle cx=${W / 2} cy=${H / 2} r="14" fill="none" stroke="#e8e2d8" strokeWidth=".8"/></g>`;
    case "mushrooms": return html`<g>${[[8, 10, 6, "#8fe6cd"], [W - 10, H - 8, 5, "#c9a24a"], [W / 2, H / 2, 7, "#d9a3ff"]].map(([x, y, r, f], i) => html`<g key=${i}><rect x=${x - 1.5} y=${y} width="3" height="7" fill="#e8e2d8"/><circle cx=${x} cy=${y} r=${r} fill=${f} opacity=".9"/></g>`)}</g>`;
    case "crystal": return html`<path d=${`M${W / 2},4 L${W - 5},${H / 2} L${W / 2},${H - 4} L5,${H / 2} Z`} fill="#8fe6cd" stroke="#2f8f78" strokeWidth="1.2" opacity=".95"/>`;
    case "rune": return html`<g><circle cx=${W / 2} cy=${H / 2} r=${Math.min(W, H) / 2 - 4} fill="none" stroke="#d9a3ff" strokeWidth="1.5" strokeDasharray="4 3"/><circle cx=${W / 2} cy=${H / 2} r=${Math.min(W, H) / 2 - 10} fill="none" stroke="#d9a3ff" strokeWidth="1"/></g>`;
    case "portal": return html`<g><ellipse cx=${W / 2} cy=${H / 2} rx=${W / 2 - 5} ry=${H / 2 - 3} fill="#5a3a8b" stroke="#d9a3ff" strokeWidth="2"/><ellipse cx=${W / 2} cy=${H / 2} rx=${W / 2 - 12} ry=${H / 2 - 9} fill="#8fe6cd" opacity=".6"/></g>`;
    case "tree": return html`<g><circle cx=${W / 2} cy=${H / 2} r=${Math.min(W, H) / 2 - 3} fill="#4f6f34" stroke="#2a3a1a" strokeWidth="1"/><circle cx=${W / 2 - 3} cy=${H / 2 - 3} r="4" fill="#6f9a4b"/></g>`;
    case "stall": case "tent": return html`<g>${box(k === "tent" ? "#9a8a62" : "#c9a24a", "#2a1f15", 2)}<path d=${`M3,${H / 2} h${W - 6}`} stroke="#8b3a3a" strokeWidth="3"/></g>`;
    case "anvil": return html`<path d=${`M5,${H / 2 - 3} h${W - 10} v4 h-6 v6 h-${W - 22} v-6 h-6 z`} fill=${iron} stroke="#2a1f15" strokeWidth="1"/>`;
    case "gallows": case "chains": return html`<g>${k === "gallows" ? html`<rect x="5" y="4" width="3" height=${H - 8} fill=${wood}/><rect x="5" y="4" width=${W - 10} height="3" fill=${wood}/><path d=${`M${W - 8},7 v8`} stroke="#9a8a62" strokeWidth="1.2"/>` : html`<path d=${`M5,${H / 2} q3,-4 6,0 t6,0 t6,0`} stroke="#9aa0a8" strokeWidth="2" fill="none"/>`}</g>`;
    case "loom": case "trough": return html`<g>${box(woodL, "#2a1f15", 2)}<rect x="6" y="6" width=${W - 12} height=${H - 12} fill=${k === "trough" ? "#3a5a6a" : "#8b3a3a"} opacity=".8"/></g>`;
    case "body": return html`<g><ellipse cx=${W / 2} cy=${H / 2} rx=${W / 2 - 4} ry="6" fill="#6a5a4a" stroke="#2a1f15" strokeWidth="1"/><circle cx="8" cy=${H / 2} r="4" fill="#d8b08a"/></g>`;
    case "stain": return html`<path d=${`M${W / 2 - 6},${H / 2} q2,-7 8,-5 q7,1 5,7 q-2,6 -8,4 q-6,-1 -5,-6z`} fill="#5a1a1a" opacity=".55"/>`;
    case "cloth": return html`<path d=${`M5,8 l6,-3 l6,4 l5,-2 l-3,8 l-6,2 l-5,-3z`} fill="#8b3a3a" opacity=".85"/>`;
    case "marks": case "footprints": return html`<g opacity=".6">${[0, 1, 2, 3].map(i => html`<ellipse key=${i} cx=${6 + i * ((W - 12) / 3)} cy=${H / 2 + (i % 2 ? 4 : -4)} rx="3" ry="4.5" fill="#2a1f15"/>`)}</g>`;
    case "egg": return html`<g>${[[W / 2 - 7, H / 2 + 2], [W / 2 + 6, H / 2 + 3], [W / 2, H / 2 - 6]].map(([x, y], i) => html`<ellipse key=${i} cx=${x} cy=${y} rx="6" ry="8" fill="#c9b89a" stroke="#5a4328" strokeWidth="1"/>`)}</g>`;
    case "cannon": return html`<g><rect x="4" y=${H / 2 - 4} width=${W - 8} height="8" rx="3" fill=${iron}/><circle cx=${W / 2} cy=${H / 2 + 7} r="3" fill="#2a1f15"/></g>`;
    case "grate": return html`<g><rect x="4" y="4" width=${W - 8} height=${H - 8} fill="#1a1612" stroke="#3a3a40"/>${[0, 1, 2].map(i => html`<rect key=${i} x="6" y=${7 + i * 6} width=${W - 12} height="2" fill="#5a5a60"/>`)}</g>`;
    case "stairs": case "ladder": case "trapdoor": return html`<g>${k === "trapdoor" ? html`<rect x="4" y="4" width=${W - 8} height=${H - 8} fill=${wood} stroke="#2a1f15"/><circle cx=${W / 2} cy=${H / 2} r="2.5" fill="none" stroke="#c9a24a" strokeWidth="1.5"/>` : html`<rect x="3" y="3" width=${W - 6} height=${H - 6} fill="#5a554d" stroke="#2a1f15"/>${[0, 1, 2, 3].map(i => html`<rect key=${i} x="5" y=${5 + i * ((H - 10) / 4)} width=${W - 10} height=${(H - 10) / 4 - 1.5} fill=${k === "ladder" ? "#8a6a44" : `rgba(255,255,255,${0.12 + i * 0.12})`}/>`)}`}${o.dir ? html`<text x=${W / 2} y=${H / 2 + 4} textAnchor="middle" fontSize="11" fontWeight="800" fill=${k === "trapdoor" ? "#efe0bb" : "#ffd27a"} fontFamily="Alegreya Sans, sans-serif">${o.dir === "up" ? "▲" : "▼"}</text>` : null}</g>`;
    default: return box("#9a8a72", "#2a1f15", 3);
  }
}
function npcTokColor(n){ return n.npcId ? "#e6bd55" : /guard|sergeant|warden|captain/i.test(n.role || "") ? "#9aa0a8" : /keeper|smith|priest|merchant|master|librarian|harbormaster|foreman|steward/i.test(n.role || "") ? "#d8b08a" : "#c9b89a"; }
function siteCanReach(site, cur, r){ if (!cur || !roomLinks(cur).includes(r.id) || roomBlocked(cur)) return false; const d = cur.doors.find(x => x.to === r.id); return !(d?.locked && !d.unlocked); }
// ---------- the floor plan ----------
function SiteMap({ c, floorId, sel, onSel, onRoom }){
  const site = siteOf(c); const loc = c.locations[c.explore.loc]; const cur = roomOf(c); const st = SITE_STYLES[site.style] || SITE_STYLES.stone;
  const fl = site.floors.find(f => f.id === floorId) || site.floors.find(f => f.id === cur.floorId); const rooms = site.rooms.filter(r => r.floorId === fl.id);
  const W = fl.w * SU, H = fl.h * SU; const busy = !!S().busy || !!c.combat;
  const shown = r => r.state !== "unseen"; const known = r => r.state === "visited" || r.state === "cleared";
  // frame what the party knows of this floor, not the whole building
  const vis = rooms.filter(shown); const bx0 = Math.max(0, Math.min(...vis.map(r => r.x)) - 1.2), by0 = Math.max(0, Math.min(...vis.map(r => r.y)) - 1.4), bx1 = Math.min(fl.w, Math.max(...vis.map(r => r.x + r.w)) + 1.2), by1 = Math.min(fl.h, Math.max(...vis.map(r => r.y + r.h)) + 1.2);
  let vw = Math.max(bx1 - bx0, 11), vh = Math.max(by1 - by0, 8); const vcx = (bx0 + bx1) / 2, vcy = (by0 + by1) / 2;
  const vb = `${(vcx - vw / 2) * SU} ${(vcy - vh / 2) * SU} ${vw * SU} ${vh * SU}`;
  const texture = st.rough ? "cave" : site.style === "wood" || site.style === "ship" ? "planks" : site.style === "field" ? "grass" : "flags";
  const doorsDrawn = new Set();
  return html`<svg viewBox=${vb} className=${"map site-map style-" + site.style} role="img" aria-label=${`Floor plan of ${loc.name}: ${fl.name}`}>
    <defs>
      <pattern id="sp-planks" width=${SU} height=${SU / 2} patternUnits="userSpaceOnUse"><rect width=${SU} height=${SU / 2} fill=${st.floor}/><path d=${`M0,0 h${SU} M${SU / 2},0 v${SU / 2}`} stroke=${st.floor2} strokeWidth="1"/></pattern>
      <pattern id="sp-flags" width=${SU} height=${SU} patternUnits="userSpaceOnUse"><rect width=${SU} height=${SU} fill=${st.floor}/><path d=${`M0,0 h${SU} v${SU}`} stroke=${st.floor2} strokeWidth="1.2" fill="none"/><path d=${`M${SU / 2},${SU / 2} h${SU / 2}`} stroke=${st.floor2} strokeWidth=".6"/></pattern>
      <pattern id="sp-cave" width=${SU * 2} height=${SU * 2} patternUnits="userSpaceOnUse"><rect width=${SU * 2} height=${SU * 2} fill=${st.floor}/><circle cx="12" cy="14" r="7" fill=${st.floor2} opacity=".7"/><circle cx="38" cy="36" r="9" fill=${st.floor2} opacity=".5"/><circle cx="40" cy="10" r="4" fill=${st.floor2} opacity=".6"/></pattern>
      <pattern id="sp-grass" width=${SU} height=${SU} patternUnits="userSpaceOnUse"><rect width=${SU} height=${SU} fill=${st.floor}/><path d="M5,20 q2,-5 4,0 M15,12 q2,-5 4,0 M20,22 q2,-5 4,0" stroke=${st.floor2} strokeWidth="1" fill="none"/></pattern>
      <pattern id="sp-unknown" width="10" height="10" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="10" height="10" fill="#2c231b"/><path d="M0,5 h10" stroke="#3a3026" strokeWidth="2"/></pattern>
      <radialGradient id="sp-glow"><stop offset="0" stopColor="#ffb347" stopOpacity=".55"/><stop offset="1" stopColor="#ffb347" stopOpacity="0"/></radialGradient>
      <radialGradient id="sp-halo"><stop offset="0" stopColor="#e6bd55" stopOpacity=".5"/><stop offset="1" stopColor="#e6bd55" stopOpacity="0"/></radialGradient>
    </defs>
    <rect x=${-W} y=${-H} width=${W * 3} height=${H * 3} fill=${site.rooms.some(r => r.outdoor) && fl.z === 0 ? "#3a4a2a" : "#1a1612"}/>
    ${rooms.filter(shown).map(r => { const x = r.x * SU, y = r.y * SU, w = r.w * SU, h = r.h * SU; const isCur = r.id === cur.id; const can = siteCanReach(site, cur, r) && fl.id === cur.floorId; const isSel = sel?.type === "room" && sel.id === r.id;
      const lit = r.light === "lit" || r.outdoor; const glows = (known(r) ? r.objects : []).filter(o => o.lit && !/extinguished|cold/.test(o.state || "") && (!o.hidden || o.found));
      return html`<g key=${r.id} className=${"sroom" + (isCur ? " cur" : "") + (can && !busy ? " can" : "") + (known(r) ? " known" : " seen")} onClick=${(e) => { e.stopPropagation(); onSel({ type: "room", id: r.id }); if (can && !busy) onRoom(r.id); }} role="button" tabIndex="0" onKeyDown=${e => { if (e.key === "Enter"){ onSel({ type: "room", id: r.id }); if (can && !busy) onRoom(r.id); } }} aria-label=${known(r) ? r.name : "Unexplored room"}>
        <rect x=${x} y=${y} width=${w} height=${h} fill=${known(r) ? `url(#sp-${texture})` : "url(#sp-unknown)"} stroke=${st.wall} strokeWidth="7" strokeLinejoin="round" rx=${st.rough ? 14 : 2}/>
        ${known(r) && r.hazard && html`<rect x=${x + 4} y=${y + 4} width=${w - 8} height=${h - 8} fill=${{ fire: "rgba(255,120,40,.18)", water: "rgba(40,90,140,.3)", gas: "rgba(120,180,60,.22)", collapse: "rgba(120,100,80,.25)", ice: "rgba(200,230,255,.3)" }[r.hazard] || "none"} rx="4"/>`}
        ${known(r) && r.objects.filter(o => (!o.hidden || o.found) && o.flat).map(o => html`<g key=${o.id} transform=${`translate(${o.x * SU} ${o.y * SU})`} className=${"sobj" + (sel?.type === "obj" && sel.id === o.id ? " sel" : "")} onClick=${(e) => { e.stopPropagation(); if (isCur) onSel({ type: "obj", id: o.id }); }}><${ObjGlyph} o=${o} style=${st}/></g>`)}
        ${known(r) && r.objects.filter(o => (!o.hidden || o.found) && !o.flat).map(o => html`<g key=${o.id} transform=${`translate(${o.x * SU} ${o.y * SU})`} className=${"sobj" + (sel?.type === "obj" && sel.id === o.id ? " sel" : "") + (isCur && (o.acts || []).length ? " act" : "")} onClick=${(e) => { e.stopPropagation(); if (isCur) onSel({ type: "obj", id: o.id }); }} role=${isCur ? "button" : undefined} aria-label=${o.name}><title>${cap(o.name)}${o.state ? ` (${o.state})` : ""}</title><${ObjGlyph} o=${o} style=${st}/>${sel?.type === "obj" && sel.id === o.id ? html`<rect x="1" y="1" width=${o.w * SU - 2} height=${o.h * SU - 2} rx="4" fill="none" stroke="#e6bd55" strokeWidth="2" strokeDasharray="3 2"/>` : null}</g>`)}
        ${!lit && known(r) && html`<rect x=${x} y=${y} width=${w} height=${h} fill=${r.light === "dark" ? "rgba(5,3,8,.52)" : "rgba(5,3,8,.28)"} rx="2" pointerEvents="none"/>`}
        ${glows.map(o => html`<circle key=${"g" + o.id} cx=${o.x * SU + o.w * SU / 2} cy=${o.y * SU + o.h * SU / 2} r=${SU * 1.8} fill="url(#sp-glow)" pointerEvents="none"/>`)}
        ${known(r) && r.npcs.filter(n => !n.dead && !n.gone).map(n => html`<g key=${n.id} transform=${`translate(${n.x * SU + SU / 2} ${n.y * SU + SU / 2})`} className=${"snpc" + (sel?.type === "npc" && sel.id === n.id ? " sel" : "")} onClick=${(e) => { e.stopPropagation(); if (isCur) onSel({ type: "npc", id: n.id }); }} role=${isCur ? "button" : undefined} aria-label=${n.name}><title>${n.name}${n.role ? `, ${n.role}` : ""}</title><circle r="10" fill=${npcTokColor(n)} stroke=${n.npcId ? "#a57f22" : "#2a1f15"} strokeWidth=${n.npcId ? 2 : 1.2}/><text y="4" textAnchor="middle" fontSize="10" fontWeight="700" fill="#2a1f15" fontFamily="Alegreya Sans, sans-serif">${n.name.replace(/^(a |an |the )/i, "").slice(0, 1).toUpperCase()}</text></g>`)}
        ${known(r) && roomBlocked(r) && html`<g transform=${`translate(${x + w / 2} ${y + h / 2})`} pointerEvents="none"><circle r="13" fill="#7e211b" stroke="#2a1f15" strokeWidth="1.5"/><text y="5" textAnchor="middle" fontSize="14" fill="#fff">☠</text>${r.enemies?.length ? html`<text y="24" textAnchor="middle" fontSize="9" fill="#ffd0c0" fontFamily="Alegreya Sans, sans-serif">${r.enemies.reduce((a, e) => a + (e.count || 1), 0)} foes</text>` : null}</g>`}
        ${known(r) && r.type === "treasure" && r.state !== "cleared" && !roomBlocked(r) && html`<text x=${x + w - 12} y=${y + 16} textAnchor="middle" fontSize="12" pointerEvents="none">💰</text>`}
        ${known(r) && r.type === "trap" && r.state !== "cleared" && html`<text x=${x + w - 12} y=${y + 16} textAnchor="middle" fontSize="12" pointerEvents="none">⚠</text>`}
        ${!known(r) && html`<text x=${x + w / 2} y=${y + h / 2 + 6} textAnchor="middle" fontSize="18" fill="#b39a74" fontFamily="Alegreya, serif" pointerEvents="none">?</text>`}
        ${known(r) && html`<text x=${x + 4} y=${y - 7} fontSize="10" fill="#f3e6c4" stroke="#1a1612" strokeWidth="2.6" paintOrder="stroke" fontFamily="Alegreya SC, serif" pointerEvents="none">${r.name}${r.private ? " (private)" : ""}</text>`}
        ${(isCur || isSel) && html`<rect x=${x} y=${y} width=${w} height=${h} fill="none" stroke=${isCur ? "#e6bd55" : "#e08a3c"} strokeWidth=${isCur ? 3.5 : 2.5} rx=${st.rough ? 14 : 2} strokeDasharray=${isSel && !isCur ? "6 4" : ""} pointerEvents="none"/>`}
        ${can && !isCur && html`<rect x=${x + 3} y=${y + 3} width=${w - 6} height=${h - 6} fill="none" stroke="#e08a3c" strokeWidth="2" rx=${st.rough ? 12 : 2} className="can-ring" pointerEvents="none"/>`}
      </g>`; })}
    ${rooms.filter(shown).flatMap(r => roomDoorsKnown(r).filter(d => d.side).map(d => { const o = siteRoom(site, d.to); const k = [r.id, d.to].sort().join("|"); if (doorsDrawn.has(k) || !o || !shown(o)) return null; doorsDrawn.add(k);
      const vert = d.side === "e" || d.side === "w"; const x = d.x * SU, y = d.y * SU; const locked = d.locked && !d.unlocked; const col = d.secret ? "#8b1e16" : locked ? "#3a3a40" : "#8a6a44";
      return html`<g key=${k} pointerEvents="none"><rect x=${vert ? x - 4.5 : x - SU / 2 + 2} y=${vert ? y - SU / 2 + 2 : y - 4.5} width=${vert ? 9 : SU - 4} height=${vert ? SU - 4 : 9} fill=${known(r) || known(o) ? col : "#3a3026"} stroke="#1a1612" strokeWidth="1" rx="1.5" strokeDasharray=${d.secret ? "3 2" : ""}/>${locked ? html`<circle cx=${x} cy=${y} r="3.2" fill="#e6bd55" stroke="#1a1612" strokeWidth=".6"/>` : null}</g>`; }))}
    ${fl.id === cur.floorId && (() => { const lead = c.characters[c.activeCharId]; const free = (() => { const taken = new Set([...cur.objects.filter(o => !o.flat).map(o => { const s = []; for (let i = 0; i < o.w; i++) for (let j = 0; j < o.h; j++) s.push(`${o.x + i},${o.y + j}`); return s; }).flat(), ...cur.npcs.map(n => `${n.x},${n.y}`)]); const cells = []; for (let x = cur.x; x < cur.x + cur.w; x++) for (let y = cur.y; y < cur.y + cur.h; y++) if (!taken.has(`${x},${y}`)) cells.push([x, y]); const cx = cur.x + (cur.w - 1) / 2, cy = cur.y + (cur.h - 1) / 2; cells.sort((a, b) => Math.hypot(a[0] - cx, a[1] - cy) - Math.hypot(b[0] - cx, b[1] - cy)); return cells[0] || [cur.x, cur.y]; })();
      return html`<g className="party-token" transform=${`translate(${free[0] * SU + SU / 2} ${free[1] * SU + SU / 2})`} pointerEvents="none"><circle r="22" fill="url(#sp-halo)" className="party-pulse"/><circle r="12" fill="#b2372d" stroke="#2a1f15" strokeWidth="1.2"/><g transform="translate(-10.5 -10.5)"><${Portrait} ch=${lead} size=${21}/></g></g>`; })()}
  </svg>`;
}
// ---------- what's in the room, and what to do about it ----------
function SitePanel({ c, floorId, setFloor, sel, setSel }){
  const s = useStore(); const site = siteOf(c); const loc = c.locations[c.explore.loc]; const r = roomOf(c); const fl = site.floors.find(f => f.id === floorId) || site.floors.find(f => f.id === r.floorId);
  const busy = !!s.busy || !!c.combat || !!c.pendingRoll; const blocked = roomBlocked(r); const guest = typeof spectating === "function" && spectating();
  const selRoom = sel?.type === "room" ? siteRoom(site, sel.id) : null; const selObj = sel?.type === "obj" ? r.objects.find(o => o.id === sel.id) : null; const selNpc = sel?.type === "npc" ? r.npcs.find(n => n.id === sel.id) : null;
  const door = selRoom ? r.doors.find(d => d.to === selRoom.id) : null; const can = selRoom && siteCanReach(site, r, selRoom);
  const people = r.npcs.filter(n => !n.dead && !n.gone); const objs = roomObjects(r).filter(o => (o.acts || []).length);
  const exits = roomDoorsKnown(r).map(d => ({ d, room: siteRoom(site, d.to) })).filter(x => x.room);
  const ex = exitInfo(c, site, r); const lastDm = [...c.log].reverse().find(e => e.kind === "dm");
  const floorsKnown = site.floors.filter(f => site.rooms.some(x => x.floorId === f.id && x.state !== "unseen"));
  const act = (o, a) => useObject(o.id, a);
  const ACT_LABEL = { examine: "Examine", search: "Search", open: o => o.prisoner && !o.prisoner.freed ? "Free the prisoner" : o.locked && !o.unlocked ? "Open (locked)" : "Open", use: o => o.kind === "bell" ? "Ring" : o.kind === "wheel" ? "Turn" : "Pull", rest: "Rest here", pray: "Pray", read: "Read", take: "Take a weapon" };
  return html`<div className="site-panel">
    <div className="row" style=${{ gap: 10 }}><div className="loc-ico"><${Icon} n=${loc.type}/></div><div className="grow"><h2 style=${{ margin: 0 }}>${loc.name}</h2><div className="faint" style=${{ fontSize: 13 }}>${cap(site.label)}${site.hostile && site.theme ? ` · ${THEMES[site.theme]?.label || ""}` : ""}${site.cleared ? " · conquered" : ""}${site.mood && !site.hostile ? ` · ${site.mood}` : ""}</div></div></div>
    ${site.blurb && html`<p className="faint" style=${{ margin: "4px 0 0", fontSize: 13 }}>${site.blurb}</p>`}
    ${floorsKnown.length > 1 && html`<div className="floor-tabs" role="tablist">${floorsKnown.map(f => html`<button key=${f.id} className=${"chip" + (f.id === fl.id ? " gold" : "")} onClick=${() => { setFloor(f.id); setSel(null); }} aria-selected=${f.id === fl.id}>${f.name}${f.id === r.floorId ? " ●" : ""}</button>`)}</div>`}
    <div className="site-room">
      <h3 className="panel-title" style=${{ marginTop: 6 }}>${r.name}<span className="faint" style=${{ fontWeight: 400, fontSize: 12.5, marginLeft: 8 }}>${r.light}${r.private ? " · private" : ""}${r.hazard ? ` · ${r.hazard}` : ""}</span></h3>
      <p className="muted" style=${{ marginTop: 0, fontSize: 14 }}>${roomDesc(r, site)}</p>
      ${blocked && !c.combat && html`<button className="btn danger" disabled=${!!s.busy} onClick=${engageRoom}><${Icon} n="swords" size=${16}/> Fight! (${r.enemies?.reduce((a, e) => a + (e.count || 1), 0)} foes)</button>`}
    </div>
    ${selObj && html`<div className="site-sel parch-inset"><b>${cap(selObj.name)}</b>${selObj.state ? html`<span className="faint"> · ${selObj.state}</span>` : ""}${selObj.note && !selObj.examined ? html`<span className="faint"> · something's off here</span>` : ""}
      <div className="row wrap" style=${{ gap: 6, marginTop: 6 }}>${(selObj.acts || []).map(a => html`<button key=${a} className="btn sm" disabled=${busy || blocked || guest && false} onClick=${() => act(selObj, a)}>${typeof ACT_LABEL[a] === "function" ? ACT_LABEL[a](selObj) : ACT_LABEL[a] || cap(a)}</button>`)}${!(selObj.acts || []).includes("examine") && html`<button className="btn sm ghost" disabled=${busy || blocked} onClick=${() => act(selObj, "examine")}>Examine</button>`}</div></div>`}
    ${selNpc && html`<div className="site-sel parch-inset"><b>${selNpc.name}</b>${selNpc.role ? html`<span className="faint"> · ${selNpc.role}${selNpc.mood ? `, ${selNpc.mood}` : ""}</span>` : ""}${selNpc.line ? html`<div className="faint" style=${{ fontSize: 13, fontStyle: "italic", marginTop: 2 }}>${selNpc.line}</div>` : null}
      <div className="row wrap" style=${{ gap: 6, marginTop: 6 }}><button className="btn sm primary" disabled=${busy || blocked} onClick=${() => talkTo(selNpc.id)}>Talk</button><button className="btn sm ghost" disabled=${busy || blocked} onClick=${() => { store.set({ tab: "adventure" }); runDM("action", { text: `I watch ${selNpc.name} closely, trying to get a read on them.`, who: onlineWho() }); }}>Observe</button></div></div>`}
    ${selRoom && selRoom.id !== r.id && html`<div className="site-sel parch-inset"><b>${selRoom.state === "unseen" ? "Unexplored" : selRoom.name}</b>${door?.locked && !door.unlocked ? html`<span className="faint"> · locked</span>` : ""}${door?.secret ? html`<span className="faint"> · secret passage</span>` : ""}${door?.kind === "stairs" || door?.kind === "ladder" ? html`<span className="faint"> · ${door.kind} ${door.dir}</span>` : door?.kind === "trapdoor" ? html`<span className="faint"> · trapdoor</span>` : ""}
      <div className="row wrap" style=${{ gap: 6, marginTop: 6 }}>
        ${door?.locked && !door.unlocked ? html`<button className="btn sm" disabled=${busy || blocked} onClick=${() => unlockDoor(selRoom.id, "key")}>Use a key</button><button className="btn sm" disabled=${busy || blocked} onClick=${() => unlockDoor(selRoom.id, "pick")}>Pick the lock</button><button className="btn sm ghost" disabled=${busy || blocked} onClick=${() => unlockDoor(selRoom.id, "force")}>Force it</button>`
        : can ? html`<button className="btn sm primary" disabled=${busy || blocked} onClick=${() => moveToRoom(selRoom.id)}>Go there</button>`
        : (selRoom.state === "visited" || selRoom.state === "cleared") ? html`<button className="btn sm" disabled=${busy || blocked} onClick=${() => goToRoom(selRoom.id)}>Walk there</button>` : html`<span className="faint" style=${{ fontSize: 12.5 }}>Not reachable from here.</span>`}
      </div></div>`}
    ${people.length > 0 && html`<div><h3 className="panel-title" style=${{ marginTop: 10 }}>People here</h3><div className="row wrap" style=${{ gap: 6 }}>${people.map(n => html`<button key=${n.id} className=${"chip" + (sel?.type === "npc" && sel.id === n.id ? " gold" : "")} onClick=${() => setSel({ type: "npc", id: n.id })}>${n.name}${n.role ? html`<span className="faint"> · ${n.role}</span>` : ""}</button>`)}</div></div>`}
    ${objs.length > 0 && html`<div><h3 className="panel-title" style=${{ marginTop: 10 }}>In the room</h3><div className="row wrap" style=${{ gap: 6 }}>${objs.map(o => html`<button key=${o.id} className=${"chip" + (sel?.type === "obj" && sel.id === o.id ? " gold" : "")} onClick=${() => setSel({ type: "obj", id: o.id })}>${cap(o.name)}${o.looted ? html`<span className="faint"> · empty</span>` : o.locked && !o.unlocked ? html`<span className="faint"> · locked</span>` : ""}</button>`)}</div></div>`}
    <div><h3 className="panel-title" style=${{ marginTop: 10 }}>Ways out</h3><div className="row wrap" style=${{ gap: 6 }}>
      ${exits.map(({ d, room }) => html`<button key=${room.id} className=${"chip" + (sel?.type === "room" && sel.id === room.id ? " gold" : "") + (siteCanReach(site, r, room) ? " can" : "")} onClick=${() => { setSel({ type: "room", id: room.id }); if (room.floorId !== fl.id) setFloor(room.floorId); }}>${d.kind === "stairs" ? (d.dir === "up" ? "▲ " : "▼ ") : d.kind === "ladder" ? (d.dir === "up" ? "▲ " : "▼ ") : d.kind === "trapdoor" ? "▼ " : ""}${room.state === "unseen" ? "?" : room.name}${d.locked && !d.unlocked ? " 🔒" : ""}</button>`)}
      ${ex && html`<button className="chip can" disabled=${busy || blocked} onClick=${useExit}>${ex.kind === "alley" ? "↩ " : ex.kind === "sewer" ? "▼ " : "▲ "}${ex.label}</button>`}
      ${r.entrance && html`<button className="chip can" disabled=${busy || blocked} onClick=${() => leaveDungeon()}>↩ Leave ${loc.name}</button>`}
    </div></div>
    <div className="col" style=${{ marginTop: 10 }}>
      ${r.service && siteTown(c, loc) && !site.hostile && html`<button className="btn sm gold" disabled=${busy} onClick=${() => { const t = siteTown(c, loc); store.set({ tab: "adventure" }); ["market","smith"].includes(r.service) ? openShop(t.id, r.service) : r.service === "library" ? runDM("action", { text: "I ask the librarian what this library holds and whether I may study here.", who: onlineWho() }) : openModal({ type: "service", svc: r.service, town: t.id }); }}><${Icon} n=${SERVICE_INFO[r.service]?.icon || "shop"} size=${15}/> ${r.service === "inn" ? "Innkeeper's services" : r.service === "market" ? "Browse the wares" : r.service === "smith" ? "The smith's wares" : r.service === "temple" ? "Temple services" : r.service === "board" ? "Notice board" : r.service === "guild" ? "Guild services" : "Ask the librarian"}</button>`}
      <button className="btn sm" disabled=${busy || r.searched || blocked} onClick=${searchRoom}>${r.searched ? "Already searched" : "Search the room (Investigation)"}</button>
      ${site.hostile && html`<button className="btn sm ghost" disabled=${busy || blocked} onClick=${restInDungeon}>Short rest${r.type === "camp" ? " (safe)" : site.cleared ? "" : " (risky)"}</button>`}
      ${!r.entrance && !blocked && html`<button className="btn sm ghost" disabled=${busy} onClick=${() => leaveDungeon()}>${site.hostile ? "Retrace your steps and leave" : `Leave ${loc.name}`}</button>`}
      <button className="btn sm ghost" onClick=${() => store.set({ tab: "adventure" })}><${Icon} n="scroll" size=${15}/> Back to the story</button>
    </div>
    ${lastDm && html`<div className="site-last"><div className="faint" style=${{ fontSize: 11.5, textTransform: "uppercase", letterSpacing: ".04em" }}>The Dungeon Master</div><div className="site-last-text">${lastDm.text.replace(/\*\*|__|\*/g, "").slice(0, 260)}${lastDm.text.length > 260 ? "…" : ""}</div></div>`}
    <p className="faint" style=${{ fontSize: 12.5 }}>Tap a glowing room to walk there. Tap furniture or people in your room to act. Searching reveals hidden doors and stashes.</p>
  </div>`;
}
// ---------- the town ----------
const ROOF = { tavern: ["#8b3a3a", "#6a2a2a"], inn: ["#8b3a3a", "#6a2a2a"], temple: ["#5a6a8b", "#44506a"], smith: ["#4a4a50", "#333338"], shop: ["#a57f22", "#7a5f18"], alchemist: ["#4f8a3f", "#3a6a2f"], market: ["#c9a24a", "#a57f22"], guardhouse: ["#6a6a70", "#4a4a50"], prison: ["#5a5a60", "#3a3a40"], hall: ["#8a6a44", "#6b4a2e"], guildhall: ["#7a4a8b", "#5a3a6a"], library: ["#5a6a8b", "#44506a"], manor: ["#8a7a5a", "#6a5a3a"], keep: ["#6a6a70", "#4a4a50"], house: ["#9a7a4e", "#7a5c3a"], warehouse: ["#7a6a5a", "#5a4a3a"], docks: ["#6b4a2e", "#4a3220"], farm: ["#c9a24a", "#9a7a2a"], stables: ["#9a7a4e", "#7a5c3a"], cemetery: ["#6f8d48", "#4f6f34"], tower: ["#5a5a70", "#3a3a50"], lighthouse: ["#e8e2d8", "#b8b0a4"], square: ["#b7a98a", "#9a8a6a"], tent: ["#9a8a62", "#7a6a42"] };
function TownMap({ c, town, sel, onSel }){
  const t = town.town; const W = t.w * TU, H = t.h * TU; const biome = BIOMES[t.biome] || BIOMES.g; const here = c.locations[c.currentLocationId]; const hereB = t.buildings.find(b => b.loc && b.loc === here?.id);
  const busy = !!S().busy || !!c.combat;
  const label = (b) => b.loc && c.locations[b.loc] ? c.locations[b.loc].name : b.kind === "house" ? "" : b.name;
  return html`<svg viewBox=${`0 0 ${W} ${H}`} className="map town-map" role="img" aria-label=${`Map of ${town.name}`}>
    <defs><pattern id="tm-grass" width="20" height="20" patternUnits="userSpaceOnUse"><rect width="20" height="20" fill=${biome.col}/><path d="M4,14 q2,-5 4,0 M13,8 q2,-5 4,0" stroke="rgba(0,0,0,.12)" strokeWidth="1" fill="none"/></pattern>
      <pattern id="tm-cobble" width="12" height="12" patternUnits="userSpaceOnUse"><rect width="12" height="12" fill="#9a8a72"/><circle cx="3" cy="3" r="2.2" fill="#8a7a62"/><circle cx="9" cy="8" r="2.4" fill="#8a7a62"/></pattern>
      <pattern id="tm-water" width="30" height="12" patternUnits="userSpaceOnUse"><rect width="30" height="12" fill="#5f8794"/><path d="M0,6 q7,-4 15,0 t15,0" stroke="#7fa6b6" strokeWidth="1.5" fill="none"/></pattern>
      <radialGradient id="tm-halo"><stop offset="0" stopColor="#e6bd55" stopOpacity=".55"/><stop offset="1" stopColor="#e6bd55" stopOpacity="0"/></radialGradient></defs>
    <rect width=${W} height=${H} fill="url(#tm-grass)"/>
    ${t.water && html`<rect x="0" y=${H - 4 * TU} width=${W} height=${4 * TU} fill="url(#tm-water)"/>`}
    ${t.streets.map((s, i) => html`<line key=${i} x1=${s.x1 * TU + (s.y1 === s.y2 ? 0 : s.w * TU / 2)} y1=${s.y1 * TU + (s.y1 === s.y2 ? s.w * TU / 2 : 0)} x2=${s.x2 * TU + (s.y1 === s.y2 ? 0 : s.w * TU / 2)} y2=${s.y2 * TU + (s.y1 === s.y2 ? s.w * TU / 2 : 0)} stroke=${s.main ? "#a08a66" : "#9a8a72"} strokeWidth=${s.w * TU} strokeLinecap="round"/>`)}
    ${t.square && html`<rect x=${t.square.x * TU} y=${t.square.y * TU} width=${t.square.w * TU} height=${t.square.h * TU} fill="url(#tm-cobble)" stroke="#6a5a42" strokeWidth="1.5" rx="4"/>`}
    ${t.trees.map((tr, i) => html`<g key=${"t" + i} transform=${`translate(${tr.x * TU + TU / 2} ${tr.y * TU + TU / 2})`} pointerEvents="none"><circle r=${TU * 0.55} fill="#4f6f34" stroke="#2a3a1a" strokeWidth=".8"/><circle cx="-2" cy="-2" r=${TU * 0.28} fill="#6f9a4b"/></g>`)}
    ${t.walls && html`<rect x=${TU * 0.3} y=${TU * 0.3} width=${W - TU * 0.6} height=${(t.water ? H - 4 * TU : H) - TU * 0.6} fill="none" stroke="#4a3a2a" strokeWidth=${TU * 0.6} rx="6" pointerEvents="none"/>`}
    ${t.gates.map((g, i) => html`<rect key=${"g" + i} x=${g.side === "w" ? 0 : g.side === "e" ? W - TU * 1.2 : g.x * TU - TU} y=${g.side === "s" ? H - TU * 1.2 : g.y * TU - TU} width=${g.side === "s" ? TU * 2 : TU * 1.2} height=${g.side === "s" ? TU * 1.2 : TU * 2} fill="#8a6a44" stroke="#2a1f15" strokeWidth="1"/>`)}
    ${t.buildings.map(b => { const x = b.x * TU, y = b.y * TU, w = b.w * TU, h = b.h * TU; const [r1, r2] = ROOF[b.kind] || ROOF.house; const isSel = sel === b.id; const open = BUILDING_KINDS[b.kind]?.open; const isHere = hereB?.id === b.id; const horiz = w >= h;
      return html`<g key=${b.id} className=${"tbuild" + (isSel ? " sel" : "") + (isHere ? " here" : "")} transform=${`translate(${x} ${y})`} onClick=${(e) => { e.stopPropagation(); onSel(b.id); }} role="button" tabIndex="0" onKeyDown=${e => { if (e.key === "Enter") onSel(b.id); }} aria-label=${label(b) || BUILDING_KINDS[b.kind]?.label || b.kind}>
        <title>${label(b) || BUILDING_KINDS[b.kind]?.label}</title>
        ${open ? html`<rect width=${w} height=${h} rx="5" fill=${b.kind === "cemetery" ? "#6f8d48" : b.kind === "docks" ? "#6b4a2e" : b.kind === "farm" ? "#c9b26a" : "url(#tm-cobble)"} stroke="#4a3a2a" strokeWidth="1.5" strokeDasharray=${b.kind === "farm" || b.kind === "cemetery" ? "4 3" : ""}/>${b.kind === "cemetery" ? [0, 1, 2, 3, 4].map(i => html`<text key=${i} x=${8 + (i % 3) * (w / 3)} y=${16 + Math.floor(i / 3) * (h / 2)} fontSize="11" fill="#e8e2d8">✝</text>`) : b.kind === "market" ? [0, 1, 2].map(i => html`<rect key=${i} x=${6 + i * (w / 3)} y=${h / 2 - 5} width=${w / 3 - 10} height="10" fill=${["#8b3a3a", "#c9a24a", "#5a6a8b"][i]} stroke="#2a1f15" strokeWidth=".6"/>`) : null}`
        : html`<rect x="2" y="3" width=${w - 4} height=${h - 4} rx="2" fill="rgba(0,0,0,.25)"/><rect width=${w} height=${h} rx="2" fill=${r1} stroke="#2a1f15" strokeWidth="1.2"/><path d=${horiz ? `M0,${h / 2} h${w}` : `M${w / 2},0 v${h}`} stroke="#2a1f15" strokeWidth="1" opacity=".7"/><path d=${horiz ? `M0,0 h${w} v${h / 2} h-${w}z` : `M0,0 h${w / 2} v${h} h-${w / 2}z`} fill=${r2} opacity=".6"/>${b.kind === "temple" ? html`<path d=${`M${w / 2},6 v${h - 12} M${w / 2 - 6},12 h12`} stroke="#e6bd55" strokeWidth="2.5"/>` : b.kind === "keep" || b.kind === "tower" || b.kind === "guardhouse" || b.kind === "prison" ? [0, 1, 2, 3].map(i => html`<rect key=${i} x=${i * (w / 4) + 2} y="-3" width=${w / 8} height="5" fill="#4a4a50"/>`) : b.kind === "smith" ? html`<circle cx=${w - 8} cy="8" r="4" fill="#ff9a3c"/>` : null}`}
        <g transform=${`translate(${w / 2 - 8} ${h / 2 - 8}) scale(.67)`} stroke=${open ? "#2a1f15" : "#f3e6c4"} strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" opacity=${b.kind === "house" ? .5 : .95}>${(ICONS[b.icon] || ICONS.home).map((p, i) => html`<path key=${i} d=${p}/>`)}</g>
        ${label(b) && html`<text x=${w / 2} y=${h + 11} textAnchor="middle" fontSize="9.5" fill="#2a1f15" stroke="#efe0bb" strokeWidth="2.4" paintOrder="stroke" fontFamily="Alegreya SC, serif" pointerEvents="none">${label(b).length > 22 ? label(b).slice(0, 21) + "…" : label(b)}</text>`}
        ${isSel && html`<rect x="-3" y="-3" width=${w + 6} height=${h + 6} rx="4" fill="none" stroke="#e08a3c" strokeWidth="2.5" strokeDasharray="5 3" pointerEvents="none"/>`}
      </g>`; })}
    ${t.features.map((f, i) => html`<g key=${"f" + i} className="tfeat" transform=${`translate(${f.x * TU + TU / 2} ${f.y * TU + TU / 2})`} onClick=${(e) => { e.stopPropagation(); onSel("f" + i); }} role="button" tabIndex="0" aria-label=${f.kind}><title>${cap(f.kind === "grate" ? "sewer grate" : f.kind === "notice" ? "notice board" : f.kind)}</title>
      ${f.kind === "well" || f.kind === "fountain" ? html`<circle r=${TU * 0.6} fill="#8f8a80" stroke="#2a1f15" strokeWidth="1"/><circle r=${TU * 0.32} fill="#5f8794"/>` : f.kind === "statue" ? html`<circle r=${TU * 0.5} fill="#a8a098" stroke="#2a1f15" strokeWidth="1"/><circle cy="-2" r="3" fill="#e8e2d8"/>` : f.kind === "notice" ? html`<rect x=${-TU * 0.6} y=${-TU * 0.4} width=${TU * 1.2} height=${TU * 0.8} fill="#8a6a44" stroke="#2a1f15"/><path d="M-5,-2 h10 M-5,2 h7" stroke="#efe0bb" strokeWidth="1"/>` : f.kind === "grate" ? html`<rect x=${-TU * 0.45} y=${-TU * 0.45} width=${TU * 0.9} height=${TU * 0.9} fill="#1a1612" stroke="#3a3a40"/><path d="M-5,-3 h10 M-5,0 h10 M-5,3 h10" stroke="#5a5a60" strokeWidth="1.2"/>` : f.kind === "campfire" ? html`<circle r=${TU * 0.5} fill="#4a4440"/><circle r=${TU * 0.28} fill="#ff9a3c"/>` : null}
      ${sel === "f" + i && html`<circle r=${TU * 0.9} fill="none" stroke="#e08a3c" strokeWidth="2" strokeDasharray="4 3"/>`}</g>`)}
    ${(() => { const lead = c.characters[c.activeCharId]; const px = hereB ? hereB.x * TU + hereB.w * TU / 2 : t.square.x * TU + t.square.w * TU / 2; const py = hereB ? hereB.y * TU - 10 : t.square.y * TU + t.square.h * TU / 2 + 8;
      return html`<g className="party-token" transform=${`translate(${px} ${py})`} pointerEvents="none"><circle r="20" fill="url(#tm-halo)" className="party-pulse"/><circle r="11" fill="#b2372d" stroke="#2a1f15" strokeWidth="1.2"/><g transform="translate(-9.5 -9.5)"><${Portrait} ch=${lead} size=${19}/></g></g>`; })()}
  </svg>`;
}
function TownPanel({ c, town, sel, setSel }){
  const s = useStore(); const t = town.town; const busy = !!s.busy || !!c.combat || !!c.pendingRoll; const b = t.buildings.find(x => x.id === sel); const f = sel && sel.startsWith("f") ? t.features[+sel.slice(1)] : null;
  const here = c.locations[c.currentLocationId]; const inside = b && b.loc && b.loc === here?.id;
  const K = b ? BUILDING_KINDS[b.kind] : null; const bl = b?.loc ? c.locations[b.loc] : null; const npcs = bl ? Object.values(c.npcs).filter(n => n.location === bl.id && n.status !== "dead") : [];
  const svcFor = { tavern: "inn", inn: "inn", market: "market", smith: "smith", temple: "temple", guildhall: "guild", hall: null, guardhouse: "board" };
  return html`<div className="site-panel">
    <div className="row" style=${{ gap: 10 }}><div className="loc-ico"><${Icon} n=${town.type}/></div><div className="grow"><h2 style=${{ margin: 0 }}>${town.name}</h2><div className="faint" style=${{ fontSize: 13 }}>${cap(town.type)} · standing: <b>${standingLabel(standing(c, town))}</b>${town.fallen ? " · occupied" : ""}</div></div></div>
    <p className="muted" style=${{ fontSize: 14 }}>${town.description || "A settlement on the road."}</p>
    ${b ? html`<div className="site-sel parch-inset"><b>${bl ? bl.name : b.kind === "house" ? "A house" : b.name}</b><span className="faint"> · ${K?.label || b.kind}</span>
      ${bl?.description && html`<div className="faint" style=${{ fontSize: 13, marginTop: 2 }}>${bl.description}</div>`}
      ${npcs.length > 0 && html`<div className="faint" style=${{ fontSize: 13, marginTop: 2 }}>Here: ${npcs.map(n => n.name).join(", ")}</div>`}
      <div className="row wrap" style=${{ gap: 6, marginTop: 6 }}>
        ${inside ? html`<span className="chip good">You are here</span>` : html`<button className="btn sm primary" disabled=${busy} onClick=${() => enterBuilding(town.id, b.id)}><${Icon} n="road" size=${14}/> ${K?.open ? "Go there" : "Go inside"}</button>`}
        ${svcFor[b.kind] && servicesOf(town).includes(svcFor[b.kind]) && html`<button className="btn sm" disabled=${busy} onClick=${() => { store.set({ tab: "adventure" }); ["market","smith"].includes(svcFor[b.kind]) ? openShop(town.id, svcFor[b.kind]) : openModal({ type: "service", svc: svcFor[b.kind], town: town.id }); }}><${Icon} n=${SERVICE_INFO[svcFor[b.kind]]?.icon || "shop"} size=${14}/> ${SERVICE_INFO[svcFor[b.kind]]?.label}</button>`}
      </div></div>`
    : f ? html`<div className="site-sel parch-inset"><b>${cap(f.kind === "grate" ? "Sewer grate" : f.kind === "notice" ? "Notice board" : f.kind)}</b><div className="faint" style=${{ fontSize: 13 }}>${f.kind === "grate" ? "An iron grate in the back alley. Something stinks below." : f.kind === "notice" ? "Bounties, decrees and lost dogs." : f.kind === "well" ? "The town's well." : f.kind === "fountain" ? "A fountain in the square." : f.kind === "statue" ? "A statue of a founder nobody remembers." : "A campfire."}</div>
      <div className="row wrap" style=${{ gap: 6, marginTop: 6 }}><button className="btn sm" disabled=${busy} onClick=${() => useTownFeature(town.id, +sel.slice(1))}>${f.kind === "grate" ? "Look for a way down" : f.kind === "notice" ? "Read the notices" : "Take a look"}</button></div></div>`
    : html`<p className="faint" style=${{ fontSize: 13 }}>Tap a building to see what it is and walk inside.</p>`}
    <div><h3 className="panel-title" style=${{ marginTop: 10 }}>Around town</h3><div className="row wrap" style=${{ gap: 6 }}>${t.buildings.filter(x => x.kind !== "house").map(x => html`<button key=${x.id} className=${"chip" + (sel === x.id ? " gold" : "")} onClick=${() => setSel(x.id)}><${Icon} n=${x.icon} size=${13}/> ${x.loc && c.locations[x.loc] ? c.locations[x.loc].name : x.name}</button>`)}</div></div>
    ${t.sewer && c.locations[t.sewer]?.discovered && html`<button className="btn sm ghost" style=${{ marginTop: 8 }} disabled=${busy} onClick=${() => enterSite(t.sewer, null, { via: "Climb down into" })}><${Icon} n="sewer" size=${15}/> Down into the ${c.locations[t.sewer].name}</button>`}
    <div className="col" style=${{ marginTop: 10 }}>
      ${servicesOf(town).length > 0 && html`<div className="row wrap" style=${{ gap: 6 }}>${servicesOf(town).map(sv => html`<button key=${sv} className="chip svc" disabled=${busy} onClick=${() => { store.set({ tab: "adventure" }); ["market","smith"].includes(sv) ? openShop(town.id, sv) : openModal({ type: "service", svc: sv, town: town.id }); }}><${Icon} n=${SERVICE_INFO[sv].icon} size=${14}/> ${SERVICE_INFO[sv].label}</button>`)}</div>`}
      <button className="btn sm ghost" onClick=${() => store.set({ tab: "adventure" })}><${Icon} n="scroll" size=${15}/> Back to the story</button>
    </div>
  </div>`;
}
// walk through rooms you already know to reach a far one (quietly, no narration on the way)
async function goToRoom(roomId){
  const c0 = C(); const site = siteOf(c0); if (!site || S().busy || c0.combat) return; const cur = roomOf(c0); const target = siteRoom(site, roomId); if (!target || target.id === cur.id) return;
  const prev = { [cur.id]: null }; const q = [cur.id]; let found = false;
  while (q.length && !found){ const id = q.shift(); const r = siteRoom(site, id); if (roomBlocked(r) && id !== cur.id) continue;
    for (const n of roomLinks(r)){ const nr = siteRoom(site, n); if (prev[n] !== undefined || !nr) continue; const d = r.doors.find(x => x.to === n); if (d?.locked && !d.unlocked) continue; if (n !== roomId && !(nr.state === "visited" || nr.state === "cleared")) continue; prev[n] = id; q.push(n); if (n === roomId){ found = true; break; } } }
  if (!found) return coopNotify("You don't know a way there yet.", "bad");
  const path = []; let v = roomId; while (v && v !== cur.id){ path.unshift(v); v = prev[v]; }
  for (let i = 0; i < path.length; i++){ await moveToRoom(path[i], { quiet: i < path.length - 1 }); const c = C(); if (!c.explore || c.combat || roomOf(c)?.id !== path[i]) return; }
}
</script>
